// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDX0N_IU2jMaPTBZZP8BF4DTWjGuzFniA',
    appId: '1:218945301609:web:cb1b19b1678c48839486f8',
    messagingSenderId: '218945301609',
    projectId: 'cookify-97c9a',
    authDomain: 'cookify-97c9a.firebaseapp.com',
    storageBucket: 'cookify-97c9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBov2tdYZlSIqiQyN3PWsOIhfjB0hRytkM',
    appId: '1:218945301609:android:632dd3c1191be8b99486f8',
    messagingSenderId: '218945301609',
    projectId: 'cookify-97c9a',
    storageBucket: 'cookify-97c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocVUWeC8-FDgr37G5t_spUcBNdua0OZs',
    appId: '1:218945301609:ios:4312fec6f2fb34279486f8',
    messagingSenderId: '218945301609',
    projectId: 'cookify-97c9a',
    storageBucket: 'cookify-97c9a.appspot.com',
    iosBundleId: 'com.example.bitirme0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocVUWeC8-FDgr37G5t_spUcBNdua0OZs',
    appId: '1:218945301609:ios:27f8b5a2e486e3b29486f8',
    messagingSenderId: '218945301609',
    projectId: 'cookify-97c9a',
    storageBucket: 'cookify-97c9a.appspot.com',
    iosBundleId: 'com.example.bitirme0.RunnerTests',
  );
}
